services:
  typesense:
    image: typesense/typesense:0.24.1
    ports:
      - "8108:8108"
    command: --data-dir /data --api-key=xyz --listen-port 8108 --enable-cors
    volumes:
      - ./typesense-data:/data

  fastapi:
    build: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_CLUSTERING_ENABLED=false
      - TOKEN=${TOKEN}
    depends_on:
      - typesense